### ISSUE TITLE
[tracer] error in run_perf_recoed

### ISSUE THREAD

**Issue by lyf-g** [upenn-acg/ocolos-public#7]
Sorry to interrupt!
When I use the './trace' command, I get an error:

Error:
cycles:u: PMU Hardware doesn't support sampling/overflow-interrupts.try 'perf stat'.
Then subsequent commands (including perf2bolt, bolt, etc.) fail to execute

Do I need to change the perf command, will it affect the performance of my ocolos? Or do I need to do something else? Maybe my computer doesn't support it?

**Comment by lyf-g** [comment]
My CPU is AMD, not Intel, what should I do?

**Comment by zyuxuan0115** [comment]
Maybe AMD processors don't support some of the perf events. 

You can use hardware events from `perf list`.  If `cycles` is in the list, then maybe you can use `cycles` instead of `cycles:u`. If there are other perf events that are not supported by perf, you may need to encode the event code as raw event. 

The fastest solution is to use an Intel processor to run the ocolos.

**Comment by lyf-g** [comment]
Thanks for your reply! I've switched to Intel!
